name: Core

on: [pull_request]

jobs:
  core_coverage_report:
    name: Selfhosted runner test
    runs-on: hw-t2b1
    env:
      TREZOR_MODEL: R
      PYOPT: 0
      BOOTLOADER_DEVEL: 1
      DISABLE_OPTIGA: 1
      PYTEST_TIMEOUT: 300
      TREZOR_PYTEST_SKIP_ALTCOINS: 1
      TT_UHUB_LOCATION: "1-2"
      TT_UHUB_PORT: "1-4"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/environment
      - run: nix-shell -p uhubctl --run uhubctl
      - run: nix-shell --run "poetry run make -C core build_firmware"
      - run: nix-shell --arg hardwareTest true --run "poetry run python ci/hardware_tests/bootstrap.py t2b1 core/build/firmware/firmware.bin"
      - run: nix-shell --run "poetry run trezorctl list"
      - run: nix-shell --run "poetry run trezorctl get-features"
      - run: |
          nix-shell --arg hardwareTest true --run "ls -l /dev/tty*"
          # TODO explain
          nix-shell --arg hardwareTest true --run "sleep 8h | tio --no-autoconnect /dev/ttyTREZOR &> trezor.log" &
          nix-shell --run "poetry run pytest -v tests/device_tests -k 'not authenticate and not recovery'"
      - run: cat trezor.log
        if: always()
#      - uses: actions/upload-artifact@v3
#        with:
#          name: core-test-hw-${{ matrix.model }}-${{ matrix.asan }}
#          path: trezor.log
#          retention-days: 7
#        if: always()
